import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { startIndiVeraServer } from '../server.mjs';
import { JsonStore } from '../src/core/store.mjs';

async function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'indivera-'));const db=path.join(dir,'db.json');fs.writeFileSync(db,JSON.stringify({suppliers:[],products:[],rfqs:[],audit:[]}));const server=await startIndiVeraServer({port:0,store:new JsonStore(db)});return{server,url:`http://127.0.0.1:${server.address().port}`};}

test('IndiVera health endpoint exposes branded modules and security headers',async(t)=>{const{server,url}=await fixture();t.after(()=>server.close());const response=await fetch(`${url}/api/indivera/health`);const data=await response.json();assert.equal(response.status,200);assert.equal(data.brand,'IndiVera');assert.deepEqual(data.modules,['IndiVera Ready','IndiVera Verified','IndiVera Match','IndiVera Passport','IndiVera Trade']);assert.equal(response.headers.get('x-content-type-options'),'nosniff');assert.match(response.headers.get('content-security-policy'),/default-src 'self'/);});
test('IndiVera Ready rejects malformed JSON',async(t)=>{const{server,url}=await fixture();t.after(()=>server.close());const response=await fetch(`${url}/api/indivera/ready/analyze`,{method:'POST',headers:{'content-type':'application/json'},body:'{bad'});assert.equal(response.status,400);});
test('API rejects non-JSON content type',async(t)=>{const{server,url}=await fixture();t.after(()=>server.close());const response=await fetch(`${url}/api/indivera/ready/analyze`,{method:'POST',headers:{'content-type':'text/plain'},body:'{}'});assert.equal(response.status,400);});
test('API never exposes stack traces',async(t)=>{const{server,url}=await fixture();t.after(()=>server.close());const response=await fetch(`${url}/api/indivera/ready/analyze`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'<script>'.repeat(1000)})});const text=await response.text();assert.ok(response.status>=400);assert.doesNotMatch(text,/at .*\.mjs:\d+/);});
test('IndiVera end-to-end supplier → product → trade RFQ flow creates valid audit chain',async(t)=>{const{server,url}=await fixture();t.after(()=>server.close());const headers={'content-type':'application/json'};const supplierRes=await fetch(`${url}/api/indivera/verified/suppliers`,{method:'POST',headers,body:JSON.stringify({name:'Test Jaipur Supplier',city:'Jaipur',region:'Rajasthan',businessVerified:true,capabilities:['table linen']})});assert.equal(supplierRes.status,201);const{supplier}=await supplierRes.json();
const productRes=await fetch(`${url}/api/indivera/ready/products`,{method:'POST',headers,body:JSON.stringify({supplierId:supplier.id,name:'Test Cotton Runner',category:'table-linen',destination:'DE',channel:'B2B',originCountry:'IN',manufacturerName:'Test Jaipur Supplier',manufacturerPostalAddress:'Jaipur, India',manufacturerEmail:'test@example.invalid',productIdentifier:'TEST-001',safetyInformation:'Reviewed; no special warning recorded.',composition:[{fibre:'cotton',percentage:100}],compositionEvidence:true,packagingSpecification:true,productionBatch:'T-1',moq:50,fobPriceEur:9.2,leadTimeDays:28,businessVerified:true,qualityEvidence:true})});assert.equal(productRes.status,201);
const tradeRes=await fetch(`${url}/api/indivera/trade/rfqs`,{method:'POST',headers,body:JSON.stringify({title:'German table runner order',destination:'DE',category:'table-linen',quantity:200,maxFobPriceEur:12,maxMoq:100,maxLeadTimeDays:35,requiredEvidence:['quality','business']})});assert.equal(tradeRes.status,201);const trade=await tradeRes.json();assert.equal(trade.module,'IndiVera Trade');assert.ok(trade.matches.length>=1);
const auditRes=await fetch(`${url}/api/indivera/audit`);const audit=await auditRes.json();assert.equal(audit.valid,true);assert.equal(audit.audit.length,3);});
test('IndiVera Passport API returns traceability record',async(t)=>{const{server,url}=await fixture();t.after(()=>server.close());const headers={'content-type':'application/json'};const supplierRes=await fetch(`${url}/api/indivera/verified/suppliers`,{method:'POST',headers,body:JSON.stringify({name:'Supplier'})});const{supplier}=await supplierRes.json();const productRes=await fetch(`${url}/api/indivera/ready/products`,{method:'POST',headers,body:JSON.stringify({supplierId:supplier.id,name:'Runner',category:'table-linen',destination:'DE',channel:'B2B',manufacturerName:'Supplier',productIdentifier:'SKU-X',composition:[{fibre:'cotton',percentage:100}]})});const{product}=await productRes.json();const response=await fetch(`${url}/api/indivera/passport/${product.id}`);const data=await response.json();assert.equal(data.module,'IndiVera Passport');assert.equal(data.passport.productId,'SKU-X');});
test('path traversal never reads package.json',async(t)=>{const{server,url}=await fixture();t.after(()=>server.close());const response=await fetch(`${url}/..%2Fpackage.json`);assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/text\/html/);const text=await response.text();assert.doesNotMatch(text,/"name"\s*:\s*"indivera"/);});
